### ISSUE TITLE
The “Add to Calendar” should reference an ics file for the recurring meeting

### ISSUE THREAD

**Issue by hexsecs** [Abhijay007/uptane-demo#7]
"Add to calendar" should result in downloading the meeting ics file.
<img width="853" alt="image" src="https://github.com/Abhijay007/uptane-demo/assets/89217603/ec27dbdc-e0b8-4bc6-a75e-2d5ecc630851">

**Comment by Abhijay007** [comment]
> "Add to calendar" should result in downloading the meeting ics file. <img alt="image" width="853" src="https://user-images.githubusercontent.com/89217603/269656899-ec27dbdc-e0b8-4bc6-a75e-2d5ecc630851.png">

okay, working on it
