### ISSUE TITLE
Latest is listed twice as “Latest (2.1.0)” and “2.1.0”.

### ISSUE THREAD

**Issue by hexsecs** [Abhijay007/uptane-demo#9]
https://abhijay007.github.io/uptane-demo/docs/learn-more/getting-started
https://abhijay007.github.io/uptane-demo/docs/2.1.0/learn-more/participate

2.1.0 says it is not the latest version.
<img width="1019" alt="image" src="https://github.com/Abhijay007/uptane-demo/assets/89217603/eac2964c-2d26-492b-98fe-aae96c310d1c">

While we want the durable 2.1.0 link, it should indicate that it is the latest (or maybe just redirect to the latest version).

**Comment by Abhijay007** [comment]
fixed via https://github.com/Abhijay007/uptane-demo/commit/3a3ce12c82bab082db91d531cef7aa578c8eef30
